package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/distr-sh/distr/internal/apierrors"
	internalctx "github.com/distr-sh/distr/internal/context"
	"github.com/distr-sh/distr/internal/types"
	"github.com/google/uuid"
	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

const (
	productServiceOutputExpr = `
		ps.id, ps.created_at, ps.slug, ps.type, ps.name, ps.summary, ps.description, ps.active, ps.sort_order,
		ps.owner_user_account_id, ps.listing_status,
		ps.price_minor, ps.price_currency
	`
	productServiceMediaOutputExpr = `
		psm.id, psm.product_service_id, psm.kind, psm.url, psm.caption, psm.sort_order
	`
)

// GetActiveProductServices returns the storefront entries a visitor can request, with their demo media.
func GetActiveProductServices(ctx context.Context) ([]types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.active AND ps.listing_status = 'live'
		ORDER BY ps.sort_order, ps.name`)
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	services, err := pgx.CollectRows(rows, pgx.RowToStructByName[types.ProductService])
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	if err := attachProductServiceMedia(ctx, services); err != nil {
		return nil, err
	}
	return services, nil
}

// GetActiveProductServiceBySlug returns apierrors.ErrNotFound for an unknown or inactive slug.
func GetActiveProductServiceBySlug(ctx context.Context, slug string) (*types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.active AND ps.listing_status = 'live' AND ps.slug = @slug`,
		pgx.NamedArgs{"slug": slug})
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	return collectOneProductService(ctx, rows)
}

// GetActiveProductServiceByID returns apierrors.ErrNotFound for an unknown or inactive id.
func GetActiveProductServiceByID(ctx context.Context, id uuid.UUID) (*types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.active AND ps.listing_status = 'live' AND ps.id = @id`,
		pgx.NamedArgs{"id": id})
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	return collectOneProductService(ctx, rows)
}

func collectOneProductService(ctx context.Context, rows pgx.Rows) (*types.ProductService, error) {
	service, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[types.ProductService])
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, apierrors.ErrNotFound
	} else if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	services := []types.ProductService{service}
	if err := attachProductServiceMedia(ctx, services); err != nil {
		return nil, err
	}
	return &services[0], nil
}

// CreateProductListing inserts a developer listing (g.iii-b) in the draft state. The slug is generated by the
// caller from the name; a collision is apierrors.ErrAlreadyExists. The owner is the developer who created it.
func CreateProductListing(ctx context.Context, listing *types.ProductService) error {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`INSERT INTO ProductService AS ps
			(slug, type, name, summary, description, active, sort_order, owner_user_account_id, listing_status,
			 price_minor, price_currency)
		VALUES (@slug, @type, @name, @summary, @description, false, 0, @owner, 'draft', @price_minor, @price_currency)
		RETURNING `+productServiceOutputExpr,
		pgx.NamedArgs{
			"slug":           listing.Slug,
			"type":           listing.Type,
			"name":           listing.Name,
			"summary":        listing.Summary,
			"description":    listing.Description,
			"owner":          listing.OwnerUserAccountID,
			"price_minor":    listing.PriceMinor,
			"price_currency": listing.PriceCurrency,
		})
	if err != nil {
		return fmt.Errorf("could not create product listing: %w", err)
	} else if created, err := pgx.CollectExactlyOneRow[types.ProductService](rows, pgx.RowToStructByName); err != nil {
		if pgerr := (*pgconn.PgError)(nil); errors.As(err, &pgerr) && pgerr.Code == pgerrcode.UniqueViolation {
			return apierrors.ErrAlreadyExists
		}
		return fmt.Errorf("could not create product listing: %w", err)
	} else {
		*listing = created
		return nil
	}
}

// GetProductListingByID returns a listing by id whatever its state, so its owner can edit a draft. apierrors.ErrNotFound
// when there is no such listing.
func GetProductListingByID(ctx context.Context, id uuid.UUID) (*types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.id = @id`,
		pgx.NamedArgs{"id": id})
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	return collectOneProductService(ctx, rows)
}

// GetProductListingByOwnerAndID is GetProductListingByID scoped to one developer, so a developer can only ever read
// their own listing. apierrors.ErrNotFound both when it does not exist and when it belongs to someone else.
func GetProductListingByOwnerAndID(ctx context.Context, ownerID, id uuid.UUID) (*types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.id = @id AND ps.owner_user_account_id = @owner`,
		pgx.NamedArgs{"id": id, "owner": ownerID})
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	return collectOneProductService(ctx, rows)
}

// ListProductListingsByOwner returns a developer's own listings, drafts included, oldest first.
func ListProductListingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceOutputExpr+`
		FROM ProductService ps
		WHERE ps.owner_user_account_id = @owner
		ORDER BY ps.created_at, ps.id`,
		pgx.NamedArgs{"owner": ownerID})
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	services, err := pgx.CollectRows(rows, pgx.RowToStructByName[types.ProductService])
	if err != nil {
		return nil, fmt.Errorf("could not query ProductService: %w", err)
	}
	if err := attachProductServiceMedia(ctx, services); err != nil {
		return nil, err
	}
	return services, nil
}

// UpdateProductListing writes the developer-editable fields of a listing. The owner is never changed here, so a
// listing cannot be reassigned. It returns the updated row, or apierrors.ErrNotFound when the id and owner do not
// name a listing.
func UpdateProductListing(ctx context.Context, listing types.ProductService) (*types.ProductService, error) {
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`UPDATE ProductService AS ps
		SET name = @name, summary = @summary, description = @description,
			listing_status = @listing_status, active = @active,
			price_minor = @price_minor, price_currency = @price_currency
		WHERE ps.id = @id AND ps.owner_user_account_id = @owner
		RETURNING `+productServiceOutputExpr,
		pgx.NamedArgs{
			"id":             listing.ID,
			"owner":          listing.OwnerUserAccountID,
			"name":           listing.Name,
			"summary":        listing.Summary,
			"description":    listing.Description,
			"listing_status": listing.ListingStatus,
			"active":         listing.Active,
			"price_minor":    listing.PriceMinor,
			"price_currency": listing.PriceCurrency,
		})
	if err != nil {
		return nil, fmt.Errorf("could not update product listing: %w", err)
	}
	return collectOneProductService(ctx, rows)
}

func attachProductServiceMedia(ctx context.Context, services []types.ProductService) error {
	if len(services) == 0 {
		return nil
	}
	ids := make([]uuid.UUID, len(services))
	index := make(map[uuid.UUID]int, len(services))
	for i, service := range services {
		ids[i] = service.ID
		index[service.ID] = i
	}
	db := internalctx.GetDb(ctx)
	rows, err := db.Query(ctx,
		`SELECT`+productServiceMediaOutputExpr+`
		FROM ProductServiceMedia psm
		WHERE psm.product_service_id = ANY(@ids)
		ORDER BY psm.sort_order, psm.id`,
		pgx.NamedArgs{"ids": ids})
	if err != nil {
		return fmt.Errorf("could not query ProductServiceMedia: %w", err)
	}
	media, err := pgx.CollectRows(rows, pgx.RowToStructByName[types.ProductServiceMedia])
	if err != nil {
		return fmt.Errorf("could not query ProductServiceMedia: %w", err)
	}
	for _, m := range media {
		i := index[m.ProductServiceID]
		services[i].Media = append(services[i].Media, m)
	}
	return nil
}
